export const TRY_SIGNUP = 'TRY_SIGNUP';
export const TRY_LOGIN = 'TRY_LOGIN';
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const ADD_BUSINESS_INCOME = 'ADD_BUSINESS_INCOME';
export const ADD_BUSINESS_EXPENSE = 'ADD_BUSINESS_EXPENSE';
export const ADD_JOB_INCOME = 'ADD_JOB_INCOME';
export const ADD_JOB_EXPENSE = 'ADD_JOB_EXPENSE';
